import { ArrowUpRight, Flag, KeyRound, Mail, ShieldCheck } from 'lucide-react';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';

const helpCards = [{ icon: KeyRound, title: '계정과 로그인', text: '비밀번호 재설정, 로그인 오류, 이메일 주소와 프로필 변경에 관한 도움입니다.' }, { icon: ShieldCheck, title: '개인정보와 탈퇴', text: '내 정보 열람·정정, 계정 탈퇴와 개인정보 삭제 요청을 안내합니다.' }, { icon: Flag, title: '신고와 안전', text: '불편한 콘텐츠나 이용자를 신고하고 차단하는 방법을 확인하세요.' }];
const questions = [['계정을 탈퇴하면 어떻게 되나요?', '앱의 계정 관리 화면에서 탈퇴를 요청할 수 있습니다. 요청 즉시 로그아웃되고 서비스 이용이 중지되며, 법령상 보관 의무가 없는 개인정보는 바로 영구 삭제됩니다. 삭제된 계정과 정보는 복구할 수 없습니다.'], ['비밀번호를 잊어버렸어요.', '로그인 화면에서 “비밀번호를 잊으셨나요?”를 선택한 뒤 가입할 때 입력한 이메일 주소를 입력하세요. 해당 주소로 비밀번호 재설정 안내가 발송됩니다. 가입 시 잘못된 이메일 주소를 입력했다면 본인 확인이 어려울 수 있습니다.'], ['신고하거나 차단하려면 어떻게 하나요?', '문제가 되는 기록·댓글·게시물 또는 이용자 화면에서 신고 또는 차단 기능을 이용해 주세요. 신고 사유를 함께 남기면 검토에 도움이 됩니다. 긴급한 위험이 있다면 지역의 긴급 신고 기관에 먼저 연락해 주세요.'], ['사진과 기록은 누가 볼 수 있나요?', '개인 기록은 본인만 볼 수 있습니다. 챌린지 방에 작성한 지출 기록, 사진, 댓글 및 게시물은 그 방의 다른 참여자에게 보일 수 있습니다.']];

export default function SupportPage() {
  return <div className="site-frame"><SiteHeader /><main className="support-main"><div className="support-layout"><div className="support-content"><header className="support-hero"><p className="eyebrow">support</p><h1>고객지원</h1><p>궁금한 점이 있으신가요? 필요한 도움을 빠르게 안내하겠습니다.</p></header><section className="help-card-grid" aria-label="도움 주제">{helpCards.map(({ icon: Icon, title, text }) => <article className="help-card" key={title}><span className="help-icon"><Icon size={46} strokeWidth={1.25} /></span><span className="yellow-rule" aria-hidden="true" /><h2>{title}</h2><p>{text}</p><a href="#contact" aria-label={`${title} 도움 요청하기`}><ArrowUpRight size={30} strokeWidth={1.35} aria-hidden="true" /></a></article>)}</section></div><aside className="support-aside"><div className="contact-card" id="contact"><Mail size={58} strokeWidth={1.2} /><h2>문의하기</h2><p>서비스 이용과 개인정보 관련 문의를 이메일로 보내 주세요.</p><a className="placeholder-contact" href="mailto:dev.youn.cheon@gmail.com">dev.youn.cheon@gmail.com</a><small>문의 내용과 사용 중인 기능을 함께 알려 주시면 더 빠르게 도와드릴 수 있어요.</small></div><div className="faq-block"><h2>자주 묻는 질문</h2><div className="faq-list">{questions.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></aside></div></main><SiteFooter /></div>;
}
